import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translation object
const translations = {
  de: {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome":
      "Willkommen zurück! Hier ist Ihre Sicherheitsmanagement-Übersicht.",
    "dashboard.setupCompany": "Firma einrichten",
    "dashboard.totalEmployees": "Mitarbeiter insgesamt",
    "dashboard.overdueObligations": "Überfällige HSE-Verpflichtungen",
    "dashboard.last7Days": "Letzte 7 Tage",
    "dashboard.incidents": "Vorfallberichte",
    "dashboard.hazards": "Gefahrenmeldungen",
    "dashboard.needsAttention": "⚠️ Benötigt Aufmerksamkeit",
    "dashboard.newReports": "📊 Neue Berichte",
    "dashboard.thisMonth": "+5 diesen Monat",
    "dashboard.healthCheckups": "Gesundheitsuntersuchungen",
    "dashboard.healthCheckupsDesc":
      "Status der Gesundheitsbeurteilungen der Mitarbeiter",
    "dashboard.taskOverview": "Aufgabenübersicht",
    "dashboard.upcomingTasks": "Anstehende Aufgaben",
    "dashboard.completedTasks": "Erledigte Aufgaben",
    "dashboard.showUpcoming": "Anstehende anzeigen",
    "dashboard.showCompleted": "Erledigte anzeigen",
    "dashboard.noTasks": "Keine Aufgaben",
    "dashboard.assignedTo": "Zugewiesen an:",
    "dashboard.unassigned": "Nicht zugewiesen",
    "dashboard.due": "Fällig:",
    "dashboard.notSet": "Nicht festgelegt",
    "dashboard.planned": "Geplant",
    "dashboard.dueStatus": "Fällig",
    "dashboard.completed": "Abgeschlossen",
    "dashboard.cancelled": "Abgebrochen",
    "dashboard.assigned": "Zugewiesen",
    "dashboard.in progress": "In Bearbeitung",
    "dashboard.expired": "Abgelaufen",
    "dashboard.high": "Hoch",
    "dashboard.medium": "Mittel",
    "dashboard.low": "Niedrig",
    "dashboard.urgent": "Dringend",
    "dashboard.normal": "Normal",

    // Profile
    "profile.title": "Profileinstellungen",
    "profile.subtitle": "Verwalten Sie Ihre Kontoinformationen",
    "profile.saveChanges": "Änderungen speichern",
    "profile.general": "Allgemein",
    "profile.security": "Sicherheit",
    "profile.preferences": "Einstellungen",
    "profile.picture": "Profilbild",
    "profile.pictureDesc": "Aktualisieren Sie Ihr Profilbild",
    "profile.changePicture": "Bild ändern",
    "profile.pictureFormat": "JPG, PNG oder GIF. Maximale Größe 2MB",
    "profile.personalInfo": "Persönliche Informationen",
    "profile.personalInfoDesc": "Aktualisieren Sie Ihre persönlichen Daten",
    "profile.firstName": "Vorname",
    "profile.lastName": "Nachname",
    "profile.email": "E-Mail",
    "profile.emailNote": "E-Mail kann nicht geändert werden",
    "profile.role": "Rolle:",
    "profile.companyId": "Firmen-ID:",
    "profile.editProfile": "Profil bearbeiten",
    "profile.changePassword": "Passwort ändern",
    "profile.changePasswordDesc":
      "Aktualisieren Sie Ihr Passwort, um Ihr Konto zu schützen",
    "profile.currentPassword": "Aktuelles Passwort",
    "profile.newPassword": "Neues Passwort",
    "profile.confirmPassword": "Neues Passwort bestätigen",
    "profile.updatePassword": "Passwort aktualisieren",
    "profile.twoFactor": "Zwei-Faktor-Authentifizierung",
    "profile.twoFactorDesc":
      "Fügen Sie Ihrem Konto eine zusätzliche Sicherheitsebene hinzu",
    "profile.enable2FA": "2FA aktivieren",
    "profile.notifications": "Benachrichtigungen",
    "profile.notificationsDesc":
      "Verwalten Sie, wie Sie Benachrichtigungen erhalten",
    "profile.emailNotifications": "E-Mail-Benachrichtigungen",
    "profile.emailNotificationsDesc":
      "Erhalten Sie E-Mail-Updates über Ihre Aktivitäten",
    "profile.smsNotifications": "SMS-Benachrichtigungen",
    "profile.smsNotificationsDesc":
      "Erhalten Sie SMS-Benachrichtigungen für dringende Angelegenheiten",
    "profile.languageSettings": "Spracheinstellungen",
    "profile.languageSettingsDesc": "Wählen Sie Ihre bevorzugte Sprache",
    "profile.language": "Sprache",
    "profile.german": "Deutsch",
    "profile.english": "Englisch",
    "profile.updated": "Profil aktualisiert",
    "profile.updatedDesc":
      "Ihre Profilinformationen wurden erfolgreich gespeichert.",

    // Common
    "common.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.loading": "Lädt...",

    // Employees
    "employees.title": "Mitarbeiter",
    "employees.description":
      "Verwalten Sie die Mitarbeiterdaten Ihres Unternehmens",
    "employees.addEmployee": "Mitarbeiter hinzufügen",
    "employees.addNew": "Neuen Mitarbeiter hinzufügen",
    "employees.enterDetails": "Geben Sie die Mitarbeiterdaten ein",
    "employees.employeeNumber": "Mitarbeiternummer",
    "employees.firstName": "Vorname",
    "employees.lastName": "Nachname",
    "employees.email": "E-Mail",
    "employees.emailOptional": "E-Mail (Optional)",
    "employees.jobRole": "Berufsbezeichnung",
    "employees.jobRolePlaceholder": "Berufsbezeichnung eingeben oder auswählen",
    "employees.department": "Abteilung",
    "employees.departmentPlaceholder": "Abteilung eingeben oder auswählen",
    "employees.hireDate": "Einstellungsdatum",
    "employees.status": "Status",
    "employees.active": "Aktiv",
    "employees.inactive": "Inaktiv",
    "employees.search": "Mitarbeiter suchen...",
    "employees.noEmployees": "Keine Mitarbeiter gefunden",
    "employees.adding": "Wird hinzugefügt...",
    "employees.addSuccess": "Mitarbeiter erfolgreich hinzugefügt",
    "employees.addError": "Fehler beim Hinzufügen des Mitarbeiters",
    "employees.loadError": "Fehler beim Laden der Mitarbeiter",
    "employees.name": "Name",
    "employees.filterStatus": "Status Filter",
    "employees.filterDepartment": "Abteilungs-Filter",
    "employees.allEmployees": "Alle Mitarbeiter",
    "employees.activeOnly": "Nur Aktive",
    "employees.inactiveOnly": "Nur Inaktive",
    "employees.allDepartments": "Alle Abteilungen",
    "employees.selectDepartment": "Abteilung auswählen",
    "employees.details": "Mitarbeiterdetails & Datensätze",
    "employees.info": "Info",
    "employees.riskProfile": "Risikoprofil",
    "employees.training": "Schulung",
    "employees.tasks": "Aufgaben",
    "employees.exposureGroup": "Expositionsgruppe",
    "employees.riskAssignments":
      "Risikobewertungen, die diesem Mitarbeiter zugewiesen sind, werden hier angezeigt.",
    "employees.trainingRecords":
      "Schulungsunterlagen für diesen Mitarbeiter werden hier angezeigt.",
    "employees.assignedTasks":
      "Aufgaben, die diesem Mitarbeiter zugewiesen sind, werden hier angezeigt.",
    "employees.required": "Erforderlich",
    "employees.optional": "Optional",
    "employees.enterJobRole":
      "Berufsbezeichnung eingeben (z.B. Sicherheitsbeauftragter)",
    "employees.noCompanyId":
      "Keine Firmen-ID gefunden. Sie müssen zuerst einem Unternehmen zugewiesen werden.",

    // Navigation / Layout
    "nav.dashboard": "Übersicht",
    "nav.employees": "Mitarbeiter",
    "nav.messages": "Nachrichten",
    "nav.investigations": "Untersuchungen",
    "nav.riskAssessments": "Risikobewertungen",
    "nav.measures": "Maßnahmen",
    "nav.training": "Schulungen",
    "nav.trainings": "Schulungen",
    "nav.incidents": "Vorfälle",
    "nav.audits": "Sicherheitsaudits",
    "nav.reports": "Berichte",
    "nav.settings": "Einstellungen",
    "nav.hseHub": "HSE Hub",
    "nav.welcomeToHseHub": "Willkommen bei HSE Hub",
    "nav.profile": "Profil",
    "nav.invoices": "Rechnungen",
    "nav.darkMode": "Dunkelmodus",
    "nav.language": "Sprache",
    "nav.signOut": "Abmelden",
    "nav.logout": "Abmelden",
    "nav.company": "Unternehmen",
    "nav.user": "Benutzer",

    // Super Admin
    "superadmin.dashboard": "Super Admin Dashboard",
    "superadmin.manageCompanies": "Unternehmen verwalten",
    "superadmin.manageSubscriptions": "Abonnements verwalten",
    "superadmin.viewAnalytics": "Analysen anzeigen",

    // Messages
    "messages.title": "Nachrichten",
    "messages.searchChannels": "Kanäle durchsuchen...",
    "messages.channels": "Kanäle",
    "messages.directMessages": "Direktnachrichten",
    "messages.newChannel": "Neuer Kanal",
    "messages.newMessage": "Neue Nachricht",
    "messages.selectChannel": "Kanal auswählen",
    "messages.selectChannelDesc":
      "Wählen Sie einen Kanal aus, um die Konversation zu starten",
    "messages.typeMessage": "Nachricht eingeben...",
    "messages.send": "Senden",
    "messages.messageSent": "Nachricht gesendet",
    "messages.messageDelivered": "Ihre Nachricht wurde zugestellt.",
    "messages.noMessages": "Keine Nachrichten noch. Starten Sie das Gespräch!",
    "messages.members": "Mitglieder",
    "messages.companyChannel": "Firmenweiter Kanal",
    "messages.directMessage": "Direktnachricht",
    "messages.messagePlaceholder": "Nachricht an",
    "messages.sendInstructions":
      "Drücken Sie Enter zum Senden, Umschalt+Enter für neue Zeile",

    // Investigations
    "investigations.title": "Untersuchungen",
    "investigations.manage": "Vorfalluntersuchungen verwalten",
    "investigations.new": "Neue Untersuchung",
    "investigations.edit": "Untersuchung bearbeiten",
    "investigations.id": "Untersuchungs-ID",
    "investigations.relatedIncident": "Zugehöriger Vorfall",
    "investigations.startDate": "Startdatum",
    "investigations.assignedTo": "Zugewiesen an",
    "investigations.status": "Status",
    "investigations.priority": "Priorität",
    "investigations.description": "Beschreibung",
    "investigations.findings": "Ergebnisse",
    "investigations.recommendations": "Empfehlungen",
    "investigations.search": "Untersuchungen durchsuchen...",
    "investigations.exportPDF": "Als PDF exportieren",
    "investigations.filterStatus": "Status filtern",
    "investigations.filterPriority": "Priorität filtern",
    "investigations.open": "Offen",
    "investigations.inProgress": "In Bearbeitung",
    "investigations.completed": "Abgeschlossen",
    "investigations.closed": "Geschlossen",
    "investigations.low": "Niedrig",
    "investigations.medium": "Mittel",
    "investigations.high": "Hoch",
    "investigations.critical": "Kritisch",
    "investigations.unassigned": "Nicht zugewiesen",
    "investigations.actions": "Aktionen",

    // Risk Assessments
    "risks.title": "Risikobewertungen",
    "risks.subtitle": "Gefährdungsbeurteilung (GBU)",
    "risks.new": "Neue Bewertung",
    "risks.riskTitle": "Risikotitel",
    "risks.description": "Beschreibung",
    "risks.category": "Risikokategorie",
    "risks.department": "Abteilung",
    "risks.likelihood": "Wahrscheinlichkeit",
    "risks.severity": "Schweregrad",
    "risks.riskScore": "Risikobewertung",
    "risks.riskLevel": "Risikoniveau",
    "risks.mitigation": "Schutzmaßnahmen",
    "risks.assessmentDate": "Bewertungsdatum",
    "risks.search": "Risiken durchsuchen...",
    "risks.selectCategory": "Kategorie auswählen",
    "risks.selectDepartment": "Abteilung auswählen",
    "risks.critical": "Kritisch",
    "risks.high": "Hoch",
    "risks.medium": "Mittel",
    "risks.low": "Niedrig",

    // Measures
    "measures.title": "Maßnahmen & Kontrollen",
    "measures.subtitle": "Maßnahmen zur Risikominderung verfolgen",
    "measures.new": "Neue Maßnahme",
    "measures.edit": "Maßnahme bearbeiten",
    "measures.measureTitle": "Maßnahmentitel",
    "measures.description": "Beschreibung",
    "measures.type": "Maßnahmentyp",
    "measures.status": "Status",
    "measures.responsiblePerson": "Verantwortliche Person",
    "measures.dueDate": "Fälligkeitsdatum",
    "measures.completionDate": "Abschlussdatum",
    "measures.verificationMethod": "Verifikationsmethode",
    "measures.search": "Maßnahmen durchsuchen...",
    "measures.exportPDF": "Als PDF exportieren",
    "measures.filterStatus": "Status filtern",
    "measures.filterType": "Typ filtern",
    "measures.preventive": "Präventiv",
    "measures.corrective": "Korrigierend",
    "measures.improvement": "Verbesserung",
    "measures.planned": "Geplant",
    "measures.inProgress": "In Bearbeitung",
    "measures.completed": "Abgeschlossen",
    "measures.cancelled": "Abgebrochen",
    "measures.actions": "Aktionen",
    "measures.noDeadline": "Keine Frist",

    // Training
    "training.title": "Schulungen",
    "training.subtitle": "Schulung & Qualifikationsmanagement",
    "training.records": "Schulungsunterlagen",
    "training.assign": "Schulung zuweisen",
    "training.employee": "Mitarbeiter",
    "training.trainingType": "Schulungstyp",
    "training.assignedDate": "Zugewiesenes Datum",
    "training.expiryDate": "Ablaufdatum",
    "training.status": "Status",
    "training.search": "Schulungen durchsuchen...",
    "training.selectEmployee": "Mitarbeiter auswählen",
    "training.selectType": "Schulungstyp auswählen",
    "training.assigned": "Zugewiesen",
    "training.inProgress": "In Bearbeitung",
    "training.completed": "Abgeschlossen",
    "training.expired": "Abgelaufen",
    "training.actions": "Aktionen",

    // Incidents
    "incidents.title": "Vorfälle & Untersuchungen",
    "incidents.description":
      "Arbeitsplatzvorfälle, Beinahe-Unfälle und Verletzungen mit Ursachenanalyse verfolgen",
    "incidents.subtitle": "Vorfälle & Beinahe-Unfälle",
    "incidents.new": "Neuer Vorfall",
    "incidents.edit": "Vorfall bearbeiten",
    "incidents.incidentNumber": "Vorfallnr.",
    "incidents.incidentTitle": "Vorfallstitel",
    "incidents.type": "Typ",
    "incidents.severity": "Schweregrad",
    "incidents.date": "Datum",
    "incidents.location": "Ort",
    "incidents.department": "Abteilung",
    "incidents.affectedEmployee": "Betroffener Mitarbeiter",
    "incidents.reportedBy": "Gemeldet von",
    "incidents.rootCause": "Ursachenanalyse",
    "incidents.immediateActions": "Sofortmaßnahmen",
    "incidents.investigationStatus": "Untersuchungsstatus",
    "incidents.search": "Vorfälle durchsuchen...",
    "incidents.searchPlaceholder": "Vorfälle durchsuchen...",
    "incidents.filterType": "Nach Typ filtern",
    "incidents.filterByType": "Nach Typ filtern",
    "incidents.filterSeverity": "Nach Schweregrad filtern",
    "incidents.filterBySeverity": "Nach Schweregrad filtern",
    "incidents.injury": "Verletzung",
    "incidents.nearMiss": "Beinahe-Unfall",
    "incidents.propertyDamage": "Sachschaden",
    "incidents.environmental": "Umwelt",
    "incidents.other": "Sonstige",
    "incidents.minor": "Geringfügig",
    "incidents.moderate": "Mäßig",
    "incidents.serious": "Schwerwiegend",
    "incidents.critical": "Kritisch",
    "incidents.fatal": "Tödlich",
    "incidents.actions": "Aktionen",
    "incidents.total": "Vorfälle insgesamt",
    "incidents.injuries": "Verletzungen",
    "incidents.nearMisses": "Beinahe-Unfälle",
    "incidents.underInvestigation": "In Untersuchung",
    "incidents.reports": "Vorfallberichte",
    "incidents.reportsDesc":
      "Vollständige Liste aller Arbeitsplatzvorfälle und Beinahe-Unfälle",
    "incidents.reportIncident": "Vorfall melden",
    "incidents.editIncident": "Vorfall bearbeiten",
    "incidents.reportNew": "Neuen Vorfall melden",
    "incidents.documentDesc":
      "Arbeitsplatzvorfall oder Beinahe-Unfall zur Untersuchung dokumentieren",
    "incidents.titlePlaceholder": "Kurze Beschreibung des Vorfalls",
    "incidents.descriptionPlaceholder":
      "Detaillierte Beschreibung dessen, was passiert ist",
    "incidents.locationPlaceholder": "Wo ist es passiert?",
    "incidents.selectDepartment": "Abteilung auswählen",
    "incidents.selectEmployee": "Mitarbeiter auswählen",
    "incidents.immediateActionsPlaceholder":
      "Was wurde unmittelbar nach dem Vorfall getan?",
    "incidents.rootCausePlaceholder": "Was hat diesen Vorfall verursacht?",
    "incidents.open": "Offen",
    "incidents.inProgress": "In Bearbeitung",
    "incidents.closed": "Geschlossen",
    "incidents.report": "Melden",
    "incidents.incident": "Vorfall",
    "incidents.allTypes": "Alle Typen",
    "incidents.allSeverities": "Alle Schweregrade",
    "incidents.noIncidents":
      "Keine Vorfälle gefunden. Melden Sie einen, um zu beginnen.",
    "incidents.status": "Status",
    "incidents.affected": "Betroffen",

    // Audits
    "audits.title": "Audits",
    "audits.subtitle": "Sicherheitsaudits",
    "audits.new": "Neues Audit",
    "audits.auditTitle": "Audit-Titel",
    "audits.category": "Audit-Kategorie",
    "audits.department": "Abteilung",
    "audits.scheduledDate": "Geplantes Datum",
    "audits.status": "Status",
    "audits.findings": "Ergebnisse",
    "audits.deficiencies": "Gefundene Mängel",
    "audits.search": "Audits durchsuchen...",
    "audits.selectCategory": "Kategorie auswählen",
    "audits.selectDepartment": "Abteilung auswählen",
    "audits.planned": "Geplant",
    "audits.inProgress": "In Bearbeitung",
    "audits.completed": "Abgeschlossen",
    "audits.actions": "Aktionen",

    // Common Actions
    "common.create": "Erstellen",
    "common.update": "Aktualisieren",
    "common.submit": "Absenden",
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.export": "Exportieren",
    "common.all": "Alle",
    "common.none": "Keine",
    "common.select": "Auswählen",
    "common.optional": "Optional",
    "common.required": "Erforderlich",
    "common.actions": "Aktionen",
    "common.by": "Von",
    "common.status": "Status",

    // Reports
    "reports.title": "HSE Berichte & Analysen",
    "reports.subtitle": "Umfassende Compliance- und Leistungs-Dashboards",
    "reports.exportPDF": "Als PDF exportieren",
    "reports.totalEmployees": "Mitarbeiter insgesamt",
    "reports.activeWorkforce": "Aktive Belegschaft",
    "reports.riskAssessments": "Risikobewertungen",
    "reports.totalGBU": "GBU-Bewertungen insgesamt",
    "reports.safetyAudits": "Sicherheitsaudits",
    "reports.completed": "abgeschlossen",
    "reports.trainingCompliance": "Schulungskonformität",
    "reports.overview": "Übersicht",
    "reports.trainingMatrix": "Schulungsmatrix",
    "reports.incidents": "Vorfälle",
    "reports.measures": "Maßnahmen",
    "reports.auditCompletion": "Audit-Abschlussstatus",
    "reports.auditMetrics": "Sicherheitsaudit-Leistungsmetriken",
    "reports.totalAudits": "Audits insgesamt",
    "reports.taskCompletion": "Aufgabenabschlussstatus",
    "reports.taskTracking": "Korrekturmaßnahmen-Verfolgung",
    "reports.totalTasks": "Aufgaben insgesamt",

    // Settings
    "settings.title": "Einstellungen",
    "settings.subtitle": "Systemkonfiguration",
    "settings.team": "Team",
    "settings.teamDesc": "Team-Mitglieder einladen und verwalten",
    "settings.userRoles": "Benutzerrollen & Berechtigungen (RBAC)",
    "settings.rolesDesc":
      "Rollen definieren und Zugriffsberechtigungen im System festlegen",
    "settings.configuration": "Konfiguration",
    "settings.configDesc": "Standorte, Abteilungen, Genehmigungen",
    "settings.catalogs": "Kataloge & Inhalte",
    "settings.catalogsDesc": "Gefahren, Maßnahmen, Risikomatrix",
    "settings.intervals": "Intervalle und Fristen",
    "settings.intervalsDesc": "Risikobewertungen, Audits, Benachrichtigungen",
    "settings.medicalCare": "Arbeitsmedizinische Vorsorge",
    "settings.medicalDesc": "G-Untersuchungsliste",
    "settings.addRole": "Benutzerdefinierte Rolle hinzufügen",
    "settings.createRole": "Benutzerdefinierte Rolle erstellen",
    "settings.roleDesc":
      "Geben Sie einen Namen für die neue Rolle ein. Sie können die Berechtigungen nach der Erstellung konfigurieren.",
    "settings.rolePlaceholder": "Rollenname (z.B. Projektleiter)",
    "settings.role": "Rolle",
    "settings.dashboard": "Dashboard",
    "settings.employees": "Mitarbeiter",
    "settings.healthCheckups": "Gesundheitsuntersuchungen",
    "settings.documents": "Dokumente",
    "settings.reports": "Berichte",
    "settings.audits": "Audits",
    "settings.settings": "Einstellungen",
    "settings.teamManagement": "Team-Management",
    "settings.teamManagementDesc":
      "Team-Mitglieder, deren Zugriff und Benutzerrollen verwalten",
    "settings.addTeamMember": "Team-Mitglied hinzufügen",
    "settings.firstName": "Vorname",
    "settings.lastName": "Nachname",
    "settings.enterFirstName": "Vorname eingeben",
    "settings.enterLastName": "Nachname eingeben",
    "settings.enterEmail": "E-Mail eingeben",
    "settings.userRole": "Benutzerrolle",
    "settings.selectRole": "Rolle auswählen",
    "settings.name": "Name",
    "settings.email": "E-Mail",
    "settings.status": "Status",
    "settings.noTeamMembers":
      "Keine Team-Mitglieder gefunden. Team-Mitglieder hinzufügen, um sie zur Plattform einzuladen.",

    // G-Investigations (Medical Care)
    "gcode.title": "G-Untersuchungsliste",
    "gcode.description":
      "Wähle hier die für dein Unternehmen relevanten G-Untersuchungen aus.",
    "gcode.saveButton": "Ausgewählte G-Codes speichern",
    "gcode.G1.1": "Silikogener Staub",
    "gcode.G1.2": "Asbestfaserhaltiger Staub",
    "gcode.G1.3": "künstliche mineralischer Staub der Kat 1 oder 2",
    "gcode.G1.4": "allgemeiner Staub",
    "gcode.G2": "Blei oder seine verbindungen",
    "gcode.G3": "Bleialkyle",
    "gcode.G4":
      "Gefahrstoffe, die Hautkrebs oder zur Krebsbildung neigende Hautveränderungen hervorrufen",
    "gcode.G5": "Glykoldinitrat oder Glycerintrinitrat",
    "gcode.G6": "Schwefelkohlenstoff",
    "gcode.G7": "Kohlenmonoxid",
    "gcode.G8": "Benzol",
    "gcode.G9": "Quecksilber oder seine verbindungen",
    "gcode.G10": "Methanol",
    "gcode.G11": "Schwefelwasserstoff",
    "gcode.G12": "Phosphor (weiß)",
    "gcode.G13": "Tetrachlormethan (Tetrachlorkohlenstoff)",
    "gcode.G14": "Trichlorethen (Trichlorethylen)",
    "gcode.G15": "Chrom-VI-Verbindungen",
    "gcode.G16": "Arsen oder seine Verbindungen",
    "gcode.G17": "Tetrachlorethen",
    "gcode.G18": "1,1,2,2-Tetrachlorethan oder Perchlorthan",
    "gcode.G19": "Dimethylformamid",
    "gcode.G20": "Lärm",
    "gcode.G21": "Kälte",
    "gcode.G22": "Säureschäden der Zähne",
    "gcode.G23": "obstruktive Atemwegserkrankungen",
    "gcode.G24": "Hauterkrankungen (mit Ausnahme von Hautkrebs)",
    "gcode.G25": "Fahr-, Steuer- und Überwachungstätigkeiten",
    "gcode.G26": "Atemschutzgeräte",
    "gcode.G27": "Isocyanate",
    "gcode.G28": "Monochlormethan (Chlormethan, Methylchlorid)",
    "gcode.G29": "Xylol / Toluol",
    "gcode.G30": "Hitze",
    "gcode.G31": "Überdruck",
    "gcode.G32": "Cadmium und seine Verbindungen",
    "gcode.G33": "aromatische Nitro- und Aminoverbindungen",
    "gcode.G34": "Fluor und seine anorganische Verbindungen",
    "gcode.G35":
      "Arbeitsaufenthalt im Ausland unter besonderen klimatischen und gesundheitlichen Belastungen",
    "gcode.G36": "Vinylchlorid",
    "gcode.G37": "Bildschirmarbeit",
    "gcode.G38": "Nickelstäube",
    "gcode.G39": "Schweißrauche",
    "gcode.G40": "Krebs erzeugende und Erbgut verändernde Gefahrstoffe",
    "gcode.G41": "Absturzgefahren",
    "gcode.G42": "Infektionsgefahren",
    "gcode.G43": "Biotechnologie",
    "gcode.G44": "Hartholzstäube",
    "gcode.G45": "Styrol",
    "gcode.G46":
      "Belastungen des Muskel- und Skelettapparates einschl. Vibrationen",
  },
  en: {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome":
      "Welcome back! Here's your safety management overview.",
    "dashboard.setupCompany": "Set Up Company",
    "dashboard.totalEmployees": "Total Employees",
    "dashboard.overdueObligations": "Overdue HSE Obligations",
    "dashboard.last7Days": "Last 7 Days",
    "dashboard.incidents": "Incident Reports",
    "dashboard.hazards": "Hazard Reports",
    "dashboard.needsAttention": "⚠️ Needs attention",
    "dashboard.newReports": "📊 New reports",
    "dashboard.thisMonth": "+5 this month",
    "dashboard.healthCheckups": "Health Check-ups",
    "dashboard.healthCheckupsDesc": "Status of employee health assessments",
    "dashboard.taskOverview": "Task Overview",
    "dashboard.upcomingTasks": "Upcoming tasks",
    "dashboard.completedTasks": "Completed tasks",
    "dashboard.showUpcoming": "Show Upcoming",
    "dashboard.showCompleted": "Show Completed",
    "dashboard.noTasks": "No tasks",
    "dashboard.assignedTo": "Assigned to:",
    "dashboard.unassigned": "Unassigned",
    "dashboard.due": "Due:",
    "dashboard.notSet": "Not set",
    "dashboard.planned": "Planned",
    "dashboard.dueStatus": "Due",
    "dashboard.completed": "Completed",
    "dashboard.cancelled": "Cancelled",
    "dashboard.assigned": "Assigned",
    "dashboard.in progress": "In Progress",
    "dashboard.expired": "Expired",
    "dashboard.high": "High",
    "dashboard.medium": "Medium",
    "dashboard.low": "Low",
    "dashboard.urgent": "Urgent",
    "dashboard.normal": "Normal",

    // Profile
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your account information",
    "profile.saveChanges": "Save Changes",
    "profile.general": "General",
    "profile.security": "Security",
    "profile.preferences": "Preferences",
    "profile.picture": "Profile Picture",
    "profile.pictureDesc": "Update your profile picture",
    "profile.changePicture": "Change Picture",
    "profile.pictureFormat": "JPG, PNG or GIF. Max size 2MB",
    "profile.personalInfo": "Personal Information",
    "profile.personalInfoDesc": "Update your personal details",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.emailNote": "Email cannot be changed",
    "profile.role": "Role:",
    "profile.companyId": "Company ID:",
    "profile.editProfile": "Edit Profile",
    "profile.changePassword": "Change Password",
    "profile.changePasswordDesc":
      "Update your password to keep your account secure",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.updatePassword": "Update Password",
    "profile.twoFactor": "Two-Factor Authentication",
    "profile.twoFactorDesc": "Add an extra layer of security to your account",
    "profile.enable2FA": "Enable 2FA",
    "profile.notifications": "Notifications",
    "profile.notificationsDesc": "Manage how you receive notifications",
    "profile.emailNotifications": "Email Notifications",
    "profile.emailNotificationsDesc":
      "Receive email updates about your activity",
    "profile.smsNotifications": "SMS Notifications",
    "profile.smsNotificationsDesc": "Receive SMS alerts for urgent matters",
    "profile.languageSettings": "Language Settings",
    "profile.languageSettingsDesc": "Choose your preferred language",
    "profile.language": "Language",
    "profile.german": "German",
    "profile.english": "English",
    "profile.updated": "Profile Updated",
    "profile.updatedDesc":
      "Your profile information has been saved successfully.",

    // Common
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading...",

    // Employees
    "employees.title": "Employees",
    "employees.description": "Manage your company's employee records",
    "employees.addEmployee": "Add Employee",
    "employees.addNew": "Add New Employee",
    "employees.enterDetails": "Enter employee details below",
    "employees.employeeNumber": "Employee Number",
    "employees.firstName": "First Name",
    "employees.lastName": "Last Name",
    "employees.email": "Email",
    "employees.emailOptional": "Email (Optional)",
    "employees.jobRole": "Job Role",
    "employees.jobRolePlaceholder": "Enter or select job role",
    "employees.department": "Department",
    "employees.departmentPlaceholder": "Enter or select department",
    "employees.hireDate": "Hire Date",
    "employees.status": "Status",
    "employees.active": "Active",
    "employees.inactive": "Inactive",
    "employees.search": "Search employees...",
    "employees.noEmployees": "No employees found",
    "employees.adding": "Adding...",
    "employees.addSuccess": "Employee added successfully",
    "employees.addError": "Failed to add employee",
    "employees.loadError": "Failed to load employees",
    "employees.name": "Name",
    "employees.filterStatus": "Status Filter",
    "employees.filterDepartment": "Department Filter",
    "employees.allEmployees": "All Employees",
    "employees.activeOnly": "Active Only",
    "employees.inactiveOnly": "Inactive Only",
    "employees.allDepartments": "All Departments",
    "employees.selectDepartment": "Select department",
    "employees.details": "Employee Details & Records",
    "employees.info": "Info",
    "employees.riskProfile": "Risk Profile",
    "employees.training": "Training",
    "employees.tasks": "Tasks",
    "employees.exposureGroup": "Exposure Group",
    "employees.riskAssignments":
      "Risk assessments assigned to this employee will appear here.",
    "employees.trainingRecords":
      "Training records for this employee will appear here.",
    "employees.assignedTasks":
      "Tasks assigned to this employee will appear here.",
    "employees.required": "Required",
    "employees.optional": "Optional",
    "employees.enterJobRole": "Enter job role (e.g., Safety Officer)",
    "employees.noCompanyId":
      "No company ID found. You need to be assigned to a company first.",

    // Navigation / Layout
    "nav.dashboard": "Dashboard",
    "nav.employees": "Employees",
    "nav.messages": "Messages",
    "nav.investigations": "Investigations",
    "nav.riskAssessments": "Risk Assessments",
    "nav.measures": "Measures",
    "nav.training": "Training",
    "nav.trainings": "Trainings",
    "nav.incidents": "Incidents",
    "nav.audits": "Audits",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.hseHub": "HSE Hub",
    "nav.welcomeToHseHub": "Welcome to HSE Hub",
    "nav.profile": "Profile",
    "nav.invoices": "Invoices",
    "nav.darkMode": "Dark mode",
    "nav.language": "Language",
    "nav.signOut": "Sign out",
    "nav.logout": "Logout",
    "nav.company": "Company",
    "nav.user": "User",

    // Super Admin
    "superadmin.dashboard": "Super Admin Dashboard",
    "superadmin.manageCompanies": "Manage Companies",
    "superadmin.manageSubscriptions": "Manage Subscriptions",
    "superadmin.viewAnalytics": "View Analytics",

    // Messages
    "messages.title": "Messages",
    "messages.searchChannels": "Search channels...",
    "messages.channels": "Channels",
    "messages.directMessages": "Direct Messages",
    "messages.newChannel": "New Channel",
    "messages.newMessage": "New Message",
    "messages.selectChannel": "Select a channel",
    "messages.selectChannelDesc": "Choose a channel to start messaging",
    "messages.typeMessage": "Type a message...",
    "messages.send": "Send",
    "messages.messageSent": "Message sent",
    "messages.messageDelivered": "Your message has been delivered.",
    "messages.noMessages": "No messages yet. Start the conversation!",
    "messages.members": "Members",
    "messages.companyChannel": "Company-wide channel",
    "messages.directMessage": "Direct message",
    "messages.messagePlaceholder": "Message",
    "messages.sendInstructions":
      "Press Enter to send, Shift+Enter for new line",

    // Investigations
    "investigations.title": "Investigations",
    "investigations.manage": "Manage incident investigations",
    "investigations.new": "New Investigation",
    "investigations.edit": "Edit Investigation",
    "investigations.id": "Investigation ID",
    "investigations.relatedIncident": "Related Incident",
    "investigations.startDate": "Start Date",
    "investigations.assignedTo": "Assigned To",
    "investigations.status": "Status",
    "investigations.priority": "Priority",
    "investigations.description": "Description",
    "investigations.findings": "Findings",
    "investigations.recommendations": "Recommendations",
    "investigations.search": "Search investigations...",
    "investigations.exportPDF": "Export PDF",
    "investigations.filterStatus": "Filter Status",
    "investigations.filterPriority": "Filter Priority",
    "investigations.open": "Open",
    "investigations.inProgress": "In Progress",
    "investigations.completed": "Completed",
    "investigations.closed": "Closed",
    "investigations.low": "Low",
    "investigations.medium": "Medium",
    "investigations.high": "High",
    "investigations.critical": "Critical",
    "investigations.unassigned": "Unassigned",
    "investigations.actions": "Actions",

    // Risk Assessments
    "risks.title": "Risk Assessments",
    "risks.subtitle": "Hazard Assessment (GBU)",
    "risks.new": "New Assessment",
    "risks.riskTitle": "Risk Title",
    "risks.description": "Description",
    "risks.category": "Risk Category",
    "risks.department": "Department",
    "risks.likelihood": "Likelihood",
    "risks.severity": "Severity",
    "risks.riskScore": "Risk Score",
    "risks.riskLevel": "Risk Level",
    "risks.mitigation": "Mitigation Measures",
    "risks.assessmentDate": "Assessment Date",
    "risks.search": "Search risks...",
    "risks.selectCategory": "Select category",
    "risks.selectDepartment": "Select department",
    "risks.critical": "Critical",
    "risks.high": "High",
    "risks.medium": "Medium",
    "risks.low": "Low",

    // Measures
    "measures.title": "Measures & Controls",
    "measures.subtitle": "Track risk mitigation measures",
    "measures.new": "New Measure",
    "measures.edit": "Edit Measure",
    "measures.measureTitle": "Measure Title",
    "measures.description": "Description",
    "measures.type": "Measure Type",
    "measures.status": "Status",
    "measures.responsiblePerson": "Responsible Person",
    "measures.dueDate": "Due Date",
    "measures.completionDate": "Completion Date",
    "measures.verificationMethod": "Verification Method",
    "measures.search": "Search measures...",
    "measures.exportPDF": "Export PDF",
    "measures.filterStatus": "Filter Status",
    "measures.filterType": "Filter Type",
    "measures.preventive": "Preventive",
    "measures.corrective": "Corrective",
    "measures.improvement": "Improvement",
    "measures.planned": "Planned",
    "measures.inProgress": "In Progress",
    "measures.completed": "Completed",
    "measures.cancelled": "Cancelled",
    "measures.actions": "Actions",
    "measures.noDeadline": "No deadline",

    // Training
    "training.title": "Training",
    "training.subtitle": "Training & Qualification Management",
    "training.records": "Training Records",
    "training.assign": "Assign Training",
    "training.employee": "Employee",
    "training.trainingType": "Training Type",
    "training.assignedDate": "Assigned Date",
    "training.expiryDate": "Expiry Date",
    "training.status": "Status",
    "training.search": "Search trainings...",
    "training.selectEmployee": "Select employee",
    "training.selectType": "Select training type",
    "training.assigned": "Assigned",
    "training.inProgress": "In Progress",
    "training.completed": "Completed",
    "training.expired": "Expired",
    "training.actions": "Actions",

    // Incidents
    "incidents.title": "Incidents & Investigations",
    "incidents.description":
      "Track workplace incidents, near misses, and injuries with root cause analysis",
    "incidents.subtitle": "Incidents & Near Misses",
    "incidents.new": "New Incident",
    "incidents.edit": "Edit Incident",
    "incidents.incidentNumber": "Incident #",
    "incidents.incidentTitle": "Incident Title",
    "incidents.type": "Type",
    "incidents.severity": "Severity",
    "incidents.date": "Date",
    "incidents.location": "Location",
    "incidents.department": "Department",
    "incidents.affectedEmployee": "Affected Employee",
    "incidents.reportedBy": "Reported By",
    "incidents.rootCause": "Root Cause Analysis",
    "incidents.immediateActions": "Immediate Actions Taken",
    "incidents.investigationStatus": "Investigation Status",
    "incidents.search": "Search incidents...",
    "incidents.searchPlaceholder": "Search incidents...",
    "incidents.filterType": "Filter by type",
    "incidents.filterByType": "Filter by type",
    "incidents.filterSeverity": "Filter by severity",
    "incidents.filterBySeverity": "Filter by severity",
    "incidents.injury": "Injury",
    "incidents.nearMiss": "Near Miss",
    "incidents.propertyDamage": "Property Damage",
    "incidents.environmental": "Environmental",
    "incidents.other": "Other",
    "incidents.minor": "Minor",
    "incidents.moderate": "Moderate",
    "incidents.serious": "Serious",
    "incidents.critical": "Critical",
    "incidents.fatal": "Fatal",
    "incidents.actions": "Actions",
    "incidents.total": "Total Incidents",
    "incidents.injuries": "Injuries",
    "incidents.nearMisses": "Near Misses",
    "incidents.underInvestigation": "Under Investigation",
    "incidents.reports": "Incident Reports",
    "incidents.reportsDesc":
      "Complete list of all workplace incidents and near misses",
    "incidents.reportIncident": "Report Incident",
    "incidents.editIncident": "Edit Incident",
    "incidents.reportNew": "Report New Incident",
    "incidents.documentDesc":
      "Document a workplace incident or near miss for investigation",
    "incidents.titlePlaceholder": "Brief description of the incident",
    "incidents.descriptionPlaceholder": "Detailed description of what happened",
    "incidents.locationPlaceholder": "Where did it occur?",
    "incidents.selectDepartment": "Select department",
    "incidents.selectEmployee": "Select employee",
    "incidents.immediateActionsPlaceholder":
      "What was done immediately after the incident?",
    "incidents.rootCausePlaceholder": "What caused this incident?",
    "incidents.open": "Open",
    "incidents.inProgress": "In Progress",
    "incidents.closed": "Closed",
    "incidents.report": "Report",
    "incidents.incident": "Incident",
    "incidents.allTypes": "All Types",
    "incidents.allSeverities": "All Severities",
    "incidents.noIncidents": "No incidents found. Report one to get started.",
    "incidents.status": "Status",
    "incidents.affected": "Affected",

    // Audits
    "audits.title": "Audits",
    "audits.subtitle": "Safety Audits",
    "audits.new": "New Audit",
    "audits.auditTitle": "Audit Title",
    "audits.category": "Audit Category",
    "audits.department": "Department",
    "audits.scheduledDate": "Scheduled Date",
    "audits.status": "Status",
    "audits.findings": "Findings",
    "audits.deficiencies": "Deficiencies Found",
    "audits.search": "Search audits...",
    "audits.selectCategory": "Select category",
    "audits.selectDepartment": "Select department",
    "audits.planned": "Planned",
    "audits.inProgress": "In Progress",
    "audits.completed": "Completed",
    "audits.actions": "Actions",

    // Common Actions
    "common.create": "Create",
    "common.update": "Update",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.all": "All",
    "common.none": "None",
    "common.select": "Select",
    "common.optional": "Optional",
    "common.required": "Required",
    "common.actions": "Actions",
    "common.by": "By",
    "common.status": "Status",

    // Reports
    "reports.title": "HSE Reports & Analytics",
    "reports.subtitle": "Comprehensive compliance and performance dashboards",
    "reports.exportPDF": "Export PDF",
    "reports.totalEmployees": "Total Employees",
    "reports.activeWorkforce": "Active workforce",
    "reports.riskAssessments": "Risk Assessments",
    "reports.totalGBU": "Total GBU assessments",
    "reports.safetyAudits": "Safety Audits",
    "reports.completed": "completed",
    "reports.trainingCompliance": "Training Compliance",
    "reports.overview": "Overview",
    "reports.trainingMatrix": "Training Matrix",
    "reports.incidents": "Incidents",
    "reports.measures": "Measures",
    "reports.auditCompletion": "Audit Completion Status",
    "reports.auditMetrics": "Safety audit performance metrics",
    "reports.totalAudits": "Total Audits",
    "reports.taskCompletion": "Task Completion Status",
    "reports.taskTracking": "Corrective action tracking",
    "reports.totalTasks": "Total Tasks",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "System Configuration",
    "settings.team": "Team",
    "settings.teamDesc": "Invite and manage team members",
    "settings.userRoles": "User Roles & Permissions (RBAC)",
    "settings.rolesDesc":
      "Define roles and their access permissions across the system",
    "settings.configuration": "Configuration",
    "settings.configDesc": "Locations, departments, approvals",
    "settings.catalogs": "Catalogs & Content",
    "settings.catalogsDesc": "Hazards, measures, risk matrix",
    "settings.intervals": "Intervals and Deadlines",
    "settings.intervalsDesc": "Risk assessments, audits, notifications",
    "settings.medicalCare": "Occupational Medical Care",
    "settings.medicalDesc": "G-Investigations list",
    "settings.addRole": "Add Custom Role",
    "settings.createRole": "Create Custom Role",
    "settings.roleDesc":
      "Enter a name for the new role. You can configure permissions after creation.",
    "settings.rolePlaceholder": "Role name (e.g., Project Manager)",
    "settings.role": "Role",
    "settings.dashboard": "Dashboard",
    "settings.employees": "Employees",
    "settings.healthCheckups": "Health Check-Ups",
    "settings.documents": "Documents",
    "settings.reports": "Reports",
    "settings.audits": "Audits",
    "settings.settings": "Settings",
    "settings.teamManagement": "Team Management",
    "settings.teamManagementDesc":
      "Manage team members, their access, and user roles",
    "settings.addTeamMember": "Add Team Member",
    "settings.firstName": "First Name",
    "settings.lastName": "Last Name",
    "settings.enterFirstName": "Enter first name",
    "settings.enterLastName": "Enter last name",
    "settings.enterEmail": "Enter email",
    "settings.userRole": "User Role",
    "settings.selectRole": "Select role",
    "settings.name": "Name",
    "settings.email": "Email",
    "settings.status": "Status",
    "settings.noTeamMembers":
      "No team members found. Add team members to invite them to the platform.",

    // G-Investigations (Medical Care)
    "gcode.title": "G-Investigations List",
    "gcode.description":
      "Select relevant German G-codes for occupational medical examinations",
    "gcode.saveButton": "Save Selected G-Codes",
    "gcode.G1.1": "Silicogenic dust",
    "gcode.G1.2": "Asbestos-containing dust",
    "gcode.G1.3": "Artificial mineral dust of category 1 or 2",
    "gcode.G1.4": "General dust",
    "gcode.G2": "Lead or its compounds",
    "gcode.G3": "Tetraethyl lead",
    "gcode.G4":
      "Hazardous substances that cause skin cancer or skin changes prone to cancer formation",
    "gcode.G5": "Glycol dinitrate or glycerol trinitrate",
    "gcode.G6": "Carbon disulfide",
    "gcode.G7": "Carbon monoxide",
    "gcode.G8": "Benzene",
    "gcode.G9": "Mercury or its compounds",
    "gcode.G10": "Methanol",
    "gcode.G11": "Hydrogen sulfide",
    "gcode.G12": "Phosphorus (white)",
    "gcode.G13": "Carbon tetrachloride",
    "gcode.G14": "Trichloroethylene",
    "gcode.G15": "Chromium VI compounds",
    "gcode.G16": "Arsenic or its compounds",
    "gcode.G17": "Tetrachloroethylene",
    "gcode.G18": "1,1,2,2-Tetrachloroethane or perchloroethane",
    "gcode.G19": "Dimethylformamide",
    "gcode.G20": "Noise",
    "gcode.G21": "Cold",
    "gcode.G22": "Acid damage to teeth",
    "gcode.G23": "Obstructive respiratory diseases",
    "gcode.G24": "Skin diseases (excluding skin cancer)",
    "gcode.G25": "Driving, steering and monitoring activities",
    "gcode.G26": "Respiratory protective equipment",
    "gcode.G27": "Isocyanates",
    "gcode.G28": "Monochloromethane (chloromethane, methyl chloride)",
    "gcode.G29": "Xylene / Toluene",
    "gcode.G30": "Heat",
    "gcode.G31": "Overpressure",
    "gcode.G32": "Cadmium and its compounds",
    "gcode.G33": "Aromatic nitro and amino compounds",
    "gcode.G34": "Fluorine and its inorganic compounds",
    "gcode.G35": "Work abroad under special climatic and health stresses",
    "gcode.G36": "Vinyl chloride",
    "gcode.G37": "Display screen work",
    "gcode.G38": "Nickel dusts",
    "gcode.G39": "Welding fumes",
    "gcode.G40": "Carcinogenic and mutagenic substances",
    "gcode.G41": "Risk of falling",
    "gcode.G42": "Infectious hazards",
    "gcode.G43": "Biotechnology",
    "gcode.G44": "Hardwood dusts",
    "gcode.G45": "Styrene",
    "gcode.G46": "Musculoskeletal stress including vibrations",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  // Default to German (de)
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "de";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
